version: '3.4'

services:

  structurizr:
    image: structurizr/lite
    ports:
      - "8080:8080"
    volumes:
      - ./docs:/usr/local/structurizr

  measurementservice:
    image: ${DOCKER_REGISTRY-}measurementservice
    build:
      context: .
      dockerfile: MeasurementService/Dockerfile
    ports: 
      - "5000:8080"
      - "5001:8081"

  patientservice:
    image: ${DOCKER_REGISTRY-}patientservice
    build:
      context: .
      dockerfile: PatientService/Dockerfile
    ports: 
      - "5002:8080"
      - "5003:8081"

  doctorui:
    image: ${DOCKER_REGISTRY-}doctorui
    build:
      context: .
      dockerfile: DoctorUI/Dockerfile
    ports: 
      - "5004:8080"
      - "5005:8081"

