version: '3.4'

services:

  structurizr:
    image: structurizr/lite
    ports:
      - "8080:8080"
    volumes:
      - ./docs:/usr/local/structurizr

  measurementservice:
    image: ${DOCKER_REGISTRY-}measurementservice
    build:
      context: .
      dockerfile: MeasurementService/Dockerfile
    ports: 
      - "5000:8080"
      - "5001:8081"
    depends_on:
      - sqlserverMeasurement
      - rabbitmq

  patientservice:
    image: ${DOCKER_REGISTRY-}patientservice
    build:
      context: .
      dockerfile: PatientService/Dockerfile
    ports: 
      - "5002:8080"
      - "5003:8081"
    depends_on:
      - sqlserverPatient
      - rabbitmq

  doctorui:
    image: ${DOCKER_REGISTRY-}doctorui
    build:
      context: .
      dockerfile: DoctorUI/Dockerfile
    ports: 
      - "5004:8080"
      - "5005:8081"
      - "5090:5090"
    depends_on:
      - measurementservice
      - rabbitmq

  sqlserverMeasurement:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=DBUser101010
    volumes:
      - sql_data_measurement:/var/opt/mssql
    ports:
      - "1434:1433"

 
  sqlserverPatient:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=DBUser101010
    volumes:
      - sql_data_patient:/var/opt/mssql
    ports:
      - "1435:1433"

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment: 
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports: 
      - "15672:15672"
      - "15674:15674"
      - "5672:5672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes: 
  sql_data_patient:
  sql_data_measurement:
  rabbitmq_data:  